# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               looks like a dance epidemic to me
tagline:             
description:         it's a blog
url:                 http://mjmaenner.github.io/blog/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Matt
  url:               http://matthewmaenner.com
  
# Custom vars
version:             1.0.0
